# Generated by Django 2.2.13 on 2020-07-17 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20200715_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=64)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.Categoria')),
            ],
            options={
                'verbose_name_plural': 'Sabores',
            },
        ),
    ]
