# Generated by Django 2.2.14 on 2020-07-29 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20200722_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=8)),
                ('detalle', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=16, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.Categoria')),
            ],
            options={
                'verbose_name': ':Detalle',
                'verbose_name_plural': ':Detalles',
                'managed': True,
            },
        ),
    ]
