# Generated by Django 2.2.14 on 2020-07-29 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_auto_20200728_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalles',
            options={'managed': True, 'verbose_name': 'Detalle:', 'verbose_name_plural': 'Detalles:'},
        ),
    ]
