# Generated by Django 2.2.13 on 2020-09-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='language_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
