# Generated by Django 2.2.13 on 2020-09-19 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
